### ISSUE TITLE
Program crashes mid-download | PermissionError: [Errno 13] Permission denied?

### ISSUE THREAD

**Issue by fttdgc** [freyta/WWE-Network-Downloader#10]
Started getting this  couple days ago and don't know if it's a Network error, my Python's error,  or something else. The last few days when running the program, it'll often start out fine and then randomly stop the download with the crash error below.

The crash itself is completely random. Sometimes it wont happen at all, but, others it will happen with every file, typically during the ts file download since that's the longest part. When it crashes the timing is completely random too, some ts files may download 10 parts, others 200, 500, etc. 

`C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader>py main.py -q 2 -t https://watch.w
we.com/episode/SmackDown-4670
Succesfully logged in
Got the video information
aac files finished downloading
596 ts files downloaded out of 840Traceback (most recent call last):
  File "main.py", line 192, in <module>
    download.download_playlist(**kwargs)
  File "C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader\download_util.py", line 11
8, in download_playlist
    self.write_data(download_data.data, "{}.{}".format(title, format))
  File "C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader\download_util.py", line 33
, in write_data
    f = open(location,"ab+")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\[_XXX_]\\Desktop\\WWE-N
etwork-Downloader/inprocess/WWE SmackDown - S2002E45 - 11-07-2002.ts'

C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader>py main.py -q 2 -t https://watch.w
we.com/episode/SmackDown-4685
Succesfully logged in
Got the video information
aac files finished downloading
134 ts files downloaded out of 818Traceback (most recent call last):
  File "main.py", line 192, in <module>
    download.download_playlist(**kwargs)
  File "C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader\download_util.py", line 11
8, in download_playlist
    self.write_data(download_data.data, "{}.{}".format(title, format))
  File "C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader\download_util.py", line 33
, in write_data
    f = open(location,"ab+")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\[_XXX_]\\Desktop\\WWE-N
etwork-Downloader/inprocess/WWE SmackDown - S2002E46 - 11-14-2002.ts'

C:\Users\[_XXX_]\Desktop\WWE-Network-Downloader>py main.py -q 2 -t https://watch.w
we.com/episode/SmackDown-4619
Succesfully logged in
Got the video information
aac files finished downloading
416 ts files downloaded out of 840`

**Comment by ditmarvisser** [comment]
Have you tried running the cmd as admin?
