### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by cpalaciosgit** [freyta/WWE-Network-Downloader#21]
Hi there,

I was able to download one video, but now I keep getting errors when trying others.  I do have a current paid subscription through my cable provider.  Any suggestions?

Succesfully logged in
Your subscription is invalid. Quitting.
Traceback (most recent call last):
  File "/home/chris/WWE-Network-Downloader-master/wwe.py", line 124, in _video_url
    exit()
  File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/WWE-Network-Downloader-master/main.py", line 113, in <module>
    video_link = account.get_video_info(EPISODE)
  File "/home/chris/WWE-Network-Downloader-master/wwe.py", line 213, in get_video_info
    video_url_resp = self._video_url(api_link['entries'][0]['item']['customFields']['DiceVideoId'])
  File "/home/chris/WWE-Network-Downloader-master/wwe.py", line 126, in _video_url
    return video_url['playerUrlCallback'], video_url['videoId']
KeyError: 'playerUrlCallback'

**Comment by freyta** [comment]
What video are you trying to download? The Network doesn't exist where I am anymore, so I can't download videos anyway but I can try and help

**Comment by cpalaciosgit** [comment]
Thank you.  I tried a few, but here’s one of the commands I try to run and got that error.
python3 main.py -t https://watch.wwe.com/episode/Royal-Rumble-1989-11877

Thanks,
-Christian

**Comment by cpalaciosgit** [comment]
Hi @freyta.  Any ideas on the issue?

Thanks!

**Comment by freyta** [comment]
Can you watch a video on the Network with your cable provider?

**Comment by cpalaciosgit** [comment]
Yeah, I have a current active subscription, which allows me to see the network through my cable provider and online.  I typically watch videos online.

**Comment by JosephFM96** [comment]
@freyta there's any option for choose the audio languages pls??
