### ISSUE TITLE
Error Downloading 

### ISSUE THREAD

**Issue by jdubs182** [freyta/WWE-Network-Downloader#25]
I am getting the below error. I logged into my account on the WWE network and played the PPV fine. Not sure why it's saying your subscription is invalid. Is anyone else getting this issue? 

Succesfully logged in
Your subscription is invalid. Quitting.
Traceback (most recent call last):
  File "J:\Media\T.V Shows\WWE Raw\Season 8\Download\wwe.py", line 124, in _video_url
    exit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\Media\T.V Shows\WWE Raw\Season 8\Download\main.py", line 113, in <module>
    video_link = account.get_video_info(EPISODE)
  File "J:\Media\T.V Shows\WWE Raw\Season 8\Download\wwe.py", line 213, in get_video_info
    video_url_resp = self._video_url(api_link['entries'][0]['item']['customFields']['DiceVideoId'])
  File "J:\Media\T.V Shows\WWE Raw\Season 8\Download\wwe.py", line 126, in _video_url
    return video_url['playerUrlCallback'], video_url['videoId']
KeyError: 'playerUrlCallback'

**Comment by jdubs182** [comment]
I got this working. I've never used a VPN on the PC I was downloading all the WWE on. I only used a chrome extension to get to the WWE site. Once I turned on a VPN for the whole PC the error went away.
