### ISSUE TITLE
Can get the downloader to work on macOS

### ISSUE THREAD

**Issue by JosephFM96** [freyta/WWE-Network-Downloader#27]
Hi I've been trying and trying with the command python3 main.py -t and then the link and I can't get nothing... I would like to know how to exactly use the downlaoder pls if anyone could make a video working and successfully downloading something.. id like to get some videos with specific times now that I get a subscription active. So wonder if anyone could help with some snapshots of the process or any video it would be really appreciated it --Thx

**Comment by JosephFM96** [comment]
i don't know if im correct but I open a new term on the downloaded folder (my credentials are already changed on the file needed)

So then I write "python3 main.py -t and link and get nothing just warnings above:

--
raceback (most recent call last):
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x103c28210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn.watch.wwe.com', port=443): Max retries exceeded with url: /api/page?path=/https://network.wwe.com/video/117663/will-the-hardys-raw-tag-team-title-reign-be-reborn-by-fate-tonight-wwecom-2017-06-12 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103c28210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/josekalel/Downloads/WWE-Network-Downloader-master/main.py", line 113, in <module>
    video_link = account.get_video_info(EPISODE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Downloads/WWE-Network-Downloader-master/wwe.py", line 131, in get_video_info
    api_link = self._session.get(f'https://cdn.watch.wwe.com/api/page?path={link}').json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/josekalel/Library/Python/3.11/lib/python/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn.watch.wwe.com', port=443): Max retries exceeded with url: /api/page?path=/https://network.wwe.com/video/117663/will-the-hardys-raw-tag-team-title-reign-be-reborn-by-fate-tonight-wwecom-2017-06-12 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103c28210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

 

------

**Comment by freyta** [comment]
I've worked on it today finally, it's hard to do because Australia no longer uses the WWE Network, so I can only VPN to another country and download whatever is free.

I have a rudimentary version working with a glitch or two. You can no longer set a start time from the timestamp in the URL since that's removed from the network, but I decided to add a version where you will be able to set the time in the HH:MM:SS format like the Network gives you.

The status so far is:

Can log in
Can grab the show title and season / episode if it exist (not all have them?)
Downloads the audio (glitches some reason. Need to look into)
Downloads the video/subtitles and chapter information

**Comment by JosephFM96** [comment]
> I've worked on it today finally, it's hard to do because Australia no longer uses the WWE Network, so I can only VPN to another country and download whatever is free.
> 
> I have a rudimentary version working with a glitch or two. You can no longer set a start time from the timestamp in the URL since that's removed from the network, but I decided to add a version where you will be able to set the time in the HH:MM:SS format like the Network gives you.
> 
> The status so far is:
> 
> Can log in Can grab the show title and season / episode if it exist (not all have them?) Downloads the audio (glitches some reason. Need to look into) Downloads the video/subtitles and chapter information
> 
> Ideally I'd love to be able to make a GUI for it because that's always been my goal, I just never got around to it

Thanks A LOT for replying... look im a graphic designer and actually learning and studying some coding I can't assure you I can make a GUI but I am able to help you in whatever you need in case of graphics also like I see you're from AUS so need to vpn for could enter to WWEN so maybe I think that I could help you out in that way maybe getting you some vpn subscription for you that could work fine and at a good and reliable speed or maybe if I can do something from my place (Mexico) ill do it... I dunno nothing of python but I could try my best to or to learn or Help you out (now that I have access to the network and also an active subscription ) so PM if I can be in any help.. sincerely I thought you will not reply me or it'll be a long time for it but GREAT that you're still "active"

**Comment by freyta** [comment]
https://github.com/freyta/WWE-Network-Downloader/tree/freyta-patch-1

Try that branch. I edited the download_util.py so that the code to check if it's a partial download doesn't show there will be every segment downloaded. Hopefully it works.

**Comment by MaxosI** [comment]
> https://github.com/freyta/WWE-Network-Downloader/tree/freyta-patch-1
> 
> Try that branch. I edited the download_util.py so that the code to check if it's a partial download doesn't show there will be every segment downloaded. Hopefully it works.

It does work although I found another bug. I tried -q 2 and the video starts 1920x1080 res and then after some mins turns to 1280x720 res.

**Comment by JosephFM96** [comment]
@freyta just found myself with this.. you know what could be?
<img width="654" alt="Captura de pantalla 2023-10-25 a la(s) 3 08 24 p m" src="https://github.com/freyta/WWE-Network-Downloader/assets/39787382/dfe158f6-6304-4cd4-92a1-fecf8b56d809">
