### ISSUE TITLE
KeyError: 'playerUrlCallback'

### ISSUE THREAD

**Issue by HolyRoller291** [freyta/WWE-Network-Downloader#30]
Hey Freyta, I'm getting this error when trying to download a link:

```
py main.py -t https://network.wwe.com/video/74194?seasonId=15625
Succesfully logged in
Traceback (most recent call last):
  File "C:\ffmpeg\main.py", line 95, in <module>
    video_link = account.get_video_info(EPISODE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ffmpeg\wwe.py", line 181, in get_video_info
    stream_url = api_link['playerUrlCallback']
                 ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'playerUrlCallback'
```

I still have WWE Network access in Germany and can watch it on the browser, but can't seem to download. Any idea what I can do to resolve?

**Comment by freyta** [comment]
Should be fixed now.
