### ISSUE TITLE
Incomplete Input

### ISSUE THREAD

**Issue by karlstone93** [freyta/WWE-Network-Downloader#31]
I've not used this for a while, i've updated to the latest version, and the latest ffmpeg but I get an incomplete input error.

it successfully exports the first 6 seconds, but that is all. It only ever shows 1 ts during the output.

Full output below - anybody have any understanding?

```
python3 main.py -q 4 -t https://network.wwe.com/video/83297 -f
Succesfully logged in
Got the video information
aac files finished downloading0
ts files finished downloading

Starting to write the metadata file

Starting to write the stream title
Finished writing the stream title

Finished writing the metadata file
ffmpeg version N-99360-g2f9a3215aa-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 59.100 / 56. 59.100
  libavcodec     58.107.100 / 58.107.100
  libavformat    58. 59.100 / 58. 59.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mpegts, from 'temp/The Undertaker.ts':
  Duration: 00:00:06.00, start: 0.100000, bitrate: 1017 kb/s
  Program 1 
    Stream #0:0[0x50]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 896x504 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
[aac @ 0x7f81fd031000] Estimating duration from bitrate, this may be inaccurate
Input #1, aac, from 'temp/The Undertaker.aac':
  Metadata:
    id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x00\x1b\xa8
  Duration: 00:00:05.92, bitrate: 5 kb/s
    Stream #1:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 5 kb/s
Input #2, ffmetadata, from 'temp/The Undertaker-metafile':
  Metadata:
    title           : The Undertaker
  Duration: N/A, start: 0.000000, bitrate: N/A
Codec 0x21000 is not in the full list.
    Stream #2:0: Data: unknown_codec
    Metadata:
      title           : The Undertaker
Output #0, mp4, to 'output/The Undertaker/The Undertaker.mp4':
  Metadata:
    id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x00\x1b\xa8
    encoder         : Lavf58.59.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 896x504 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 5 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  180 fps=0.0 q=-1.0 Lsize=     717kB time=00:00:06.01 bitrate= 975.9kbits/s speed=1.02e+03x    
video:708kB audio:4kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.762884%
Traceback (most recent call last):
  File "main.py", line 224, in <module>
    database.db_upd(video_link[2], video_link[1], str(video_selections[0][0]), partial_download, int(time.time()))
  File "/Applications/WWE-Network-Downloader-2/db_util.py", line 39, in db_upd
    self.c.execute(f"UPDATE downloads SET name = '{video_name}', quality = '{video_qual}', partial_download = '{partial}', date = '{timestamp}' WHERE id = {video_id}")
sqlite3.OperationalError: incomplete input
```

**Comment by KaoUni** [comment]
Hi, I'm having the same issue, were you able to solve it?

**Comment by karlstone93** [comment]
Yes, it should be fixed in the latest release, although, I downloaded it and it didn’t fix my issue.

But when comparing the code in my main.py against that on here, I was missing a small part in the section that checks for the inputted start and end times. It needed a bit that said, if these aren’t inputted, to just do it all.

I can’t remember the exact bit off the top of my head, but it would be worth you comparing the code with the one on here. It’s only a small bit that needs adding.

If you haven’t sorted it by this evening, I can have a look when I’m on my Mac.

**Comment by KaoUni** [comment]
No worries, I'll try have a look. 

If you can find out out when you get a moment,m that would be much appreciated.

**Comment by karlstone93** [comment]
Can you paste the contents of your main.py to pastebin or something like that and drop the link here for me to look at?

**Comment by freyta** [comment]
Are you guys getting this error only after having already downloaded a video? I just tried your command (with the keep arg and setting the quality to 6) and it worked for me when I downloaded it the first time..

```
python main.py -q 6 -t https://network.wwe.com/video/83297 -f -k
Succesfully logged in
Got the video information
aac files finished downloading 5455
ts files finished downloadingf 545

Starting to write the metadata file
Starting to write the stream title

Finished writing the stream title

Finished writing the metadata file
ffmpeg version 4.3.1-2020-11-19-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'temp/The Undertaker.ts':
  Duration: 00:54:26.53, start: 0.100000, bitrate: 460 kb/s
  Program 1
    Stream #0:0[0x50]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 896x504 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
[aac @ 00000181e2ba6100] Estimating duration from bitrate, this may be inaccurate
Input #1, aac, from 'temp/The Undertaker.aac':
  Metadata:
    id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x00\x1b\xa8
  Duration: 36:04:41.11, bitrate: 4 kb/s
    Stream #1:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 4 kb/s
Input #2, ffmetadata, from 'temp/The Undertaker-metafile':
  Metadata:
    title           : The Undertaker
  Duration: N/A, start: 0.000000, bitrate: N/A
Codec 0x21000 is not in the full list.
    Stream #2:0: Data: unknown_codec
    Metadata:
      title           : The Undertaker
Output #0, mp4, to 'output/The Undertaker/The Undertaker.mp4':
  Metadata:
    id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x00\x1b\xa8
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 896x504 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 4 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=97996 fps=68747 q=-1.0 Lsize=  247112kB time=00:54:26.50 bitrate= 619.7kbits/s speed=2.29e+03x
video:168081kB audio:77253kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.725007%
Inserted the video into the database
```

**Comment by karlstone93** [comment]
It was for all videos - it just downloaded the first segment only.

I went through all the recent commits and I think it was commit edb9724 that fixed this.

However, I downloaded the latest version of the project at the time (Jan 24) and that didn't have the commit from Oct 23 in it - but when I manually updated my code, it worked.

I'm fairly sure it was commit edb9724, that's what I was going to check in KaoUni's code - but I can't be sure as it was a few months ago now...

**Comment by KaoUni** [comment]
> Can you paste the contents of your main.py to pastebin or something like that and drop the link here for me to look at?

Hey mate, here is my main.py https://pastebin.com/3iTnfTV9

**Comment by karlstone93** [comment]
Pretty much the same as mine, so not sure it's exactly the same issue.

Can you post the output when you try to download a video?

**Comment by KaoUni** [comment]
It's a different error to what I was getting before. But it's still not working: 

https://pastebin.com/1qbiPvEB

**Comment by tr3v0rb** [comment]
hi all, don't suppose this has been fixed yet or if there is a way for me to do it?

**Comment by KaoUni** [comment]
Hi. What I did was download the latest release, but then I replaced one of the scripts with a previous version that had some changes made to it. I can't remember exactly which script I replaced or the version, it may have been download_util.py. But I can confirm when I finish work in a few hours

**Comment by KaoUni** [comment]
I used this version of download_util.py: https://github.com/freyta/WWE-Network-Downloader/blob/freyta-patch-1/download_util.py
