### ISSUE TITLE
Not getting correct m3u8 info...?

### ISSUE THREAD

**Issue by mighty0n3** [freyta/WWE-Network-Downloader#34]
Me again.. ;)

I tried downloading some old stuff but it seems like that the m3u8 info is incomplete - or maybe I just do something wrong.
Command was _python3 main.py -t https://network.wwe.com/video/67248?seasonId=15071_

Result [is here ](https://pastebin.com/hUUecgnf)

Thanks for your assistance

**Comment by freyta** [comment]
I don't have a full subscription, so can you post the output of the m3u8 file it is trying to download?

You can add the code ```print(index_m3u8_obj.dumps())``` to line 141 to assist.

**Comment by mighty0n3** [comment]
Sure - [here](https://pastebin.com/p7PVs5E9) it is

**Comment by freyta** [comment]
Seems to be unavailable. Can you post it again?

**Comment by mighty0n3** [comment]
[let's try pastes.io then ;D](https://pastes.io/lanjfvowqr)

**Comment by karlstone93** [comment]
Can you paste the contents of your main.py to pastebin or something like that and drop the link here for me to look at?

**Comment by freyta** [comment]
Sorry for the late reply.
Can you post the total length of the playlist? On line 114 of download_util.py add the line ```        print(total_length)``` and it should print out how long the video is.

**Comment by mighty0n3** [comment]
@karlstone93 https://pastebin.com/D5mvyb7z
@freyta https://pastes.io/mwjedsbqbr

**Comment by freyta** [comment]
Is this still happening?

**Comment by mighty0n3** [comment]
Unfortunately, yes. I also tried several different videos but still the same.

Besides, I newly cloned the repo (just in case I missed changes meanwhile) but there seems to be a problem with wwe.py


> Traceback (most recent call last):
>   File "/*****/WWE-Network-Downloader/main.py", line 3, in <module>
>     import wwe
>   File "/*****/WWE-Network-Downloader/wwe.py", line 145
>     for i in chapters:
>                       ^
> IndentationError: unindent does not match any outer indentation level

**Comment by crafciak31** [comment]
Hello, I may have simillar problems as well, and since I'm on Windows instead of Linux, and I'm also an amateur I don't know how much is that my problem, but I have the exact same error as the person above. 

> C:\WWE-Network-Downloader-master> python main.py -t https://network.wwe.com/video/609920
C:\WWE-Network-Downloader-master\wwe.py:10: SyntaxWarning: invalid escape sequence '\d'
  time_matches =  re.match("\\b(\d{2}):\\b(\d{2}):\\b(\d{2})", time)
Traceback (most recent call last):
  File "C:\WWE-Network-Downloader-master\main.py", line 3, in <module>
    import wwe
  File "C:\WWE-Network-Downloader-master\wwe.py", line 145
    for i in chapters:
                      ^
IndentationError: unindent does not match any outer indentation level
