### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by tr3v0rb** [freyta/WWE-Network-Downloader#35]
Hi all,

Wondering where I am going wrong? 

Cheers 

Trev

C:\Users\trevo\Desktop\WWE-Network-Downloader-master>python3 main.py -t https://watch.wwe.com/episode/SmackDown-130268
C:\Users\trevo\Desktop\WWE-Network-Downloader-master\wwe.py:10: SyntaxWarning: invalid escape sequence '\d'
  time_matches =  re.match("\\b(\d{2}):\\b(\d{2}):\\b(\d{2})", time)
Traceback (most recent call last):
  File "C:\Users\trevo\Desktop\WWE-Network-Downloader-master\main.py", line 3, in <module>
    import wwe
  File "C:\Users\trevo\Desktop\WWE-Network-Downloader-master\wwe.py", line 145
    for i in chapters:
                      ^
IndentationError: unindent does not match any outer indentation level

C:\Users\trevo\Desktop\WWE-Network-Downloader-master>

**Comment by tr3v0rb** [comment]
space missing at beginning of line 145 in wwe.py

Make sure "for" is in line with the indentation
