### ISSUE TITLE
Series without info

### ISSUE THREAD

**Issue by tomjoppen** [freyta/WWE-Network-Downloader#4]
Dear 

Some downloads fail with the following message:
C:\tmp\WWE-Network-Downloader-master>python main.py -t https://watch.wwe.com/episode/WWE-NXT-9393
Succesfully logged in
Got the video information
aac files finished downloadingf 472
ts files finished downloadingf 472

Starting to wrtie the metadata file
Finished writing the metadata title

Writing stream title
Finished writing stream title

Traceback (most recent call last):
  File "main.py", line 171, in <module>
    series_info = kodi_nfo.get_show_info(EPISODE)
  File "C:\tmp\WWE-Network-Downloader-master\kodi_nfo.py", line 186, in get_show_info
    i = show_json['entries'][0]['item']
KeyError: 'item'

**Comment by tomjoppen** [comment]
Fixed it by changing kodi_nfp.py 
186:  i = show_json['entries'][0]['item']
by this: 
   try:
        i = show_json['entries'][0]['item']
    except KeyError:
        return "Various", "Various", "", ""
    else:
